const SIGNATURE_TYPES = {
  PERFORMER_1: "PB01",
  PERFORMER_2: "PB02",
  REVIEWER: "RB01",
};

const SIGNATURE_ORDER = {
  [SIGNATURE_TYPES.PERFORMER_1]: 1,
  [SIGNATURE_TYPES.PERFORMER_2]: 2,
  [SIGNATURE_TYPES.REVIEWER]: 3,
};

export { SIGNATURE_TYPES, SIGNATURE_ORDER };
